"""Inverse dynamics: recovering deployment from a speed trace.

The round-trip is the test that matters. Run the forward model under a known
deployment, hand only the resulting speed trace back to the inversion, and it must
find the same electrical energy — with nothing left unexplained, because the lap was
generated by the very model the inversion assumes.
"""

from __future__ import annotations

import numpy as np
import pytest

from energy.battery import BatteryState
from physics.inverse import ice_power_floor, infer_deployment
from physics.simulate import simulate_lap
from physics.vehicle import VehicleModel


def vehicle(**over) -> VehicleModel:
    base = dict(
        mass_kg=778.0, cd_a=0.968, crr=0.012, air_density=1.17, p_ice_w=400_000.0,
        driveline_efficiency=0.95, cl_a=5.586, mu_lat=1.753, mu_brake=1.386,
        regen_efficiency=0.90, f_offthrottle_n=1197.0, a_lat_ceiling=44.4,
        cd_a_low=0.906,
    )
    base.update(over)
    return VehicleModel(**base)


def track(n_straight: int = 220, n_corner: int = 40):
    seg = np.concatenate([np.full(n_straight, 1e-7), np.full(n_corner, 1.0 / 60.0)])
    curvature = np.concatenate([seg, seg])
    return curvature, np.zeros_like(curvature), 5.0


def forward(deploy: np.ndarray, veh: VehicleModel):
    curvature, gradient, step = track()
    res = simulate_lap(curvature, gradient, step, veh, deploy,
                       BatteryState(soc_j=4_000_000.0))
    # Throttle and brake as a driver would have reported them.
    throttle = np.where(res.braking, 0.0, 100.0)
    return curvature, gradient, step, res, throttle, res.braking


def test_round_trip_recovers_the_deployed_energy():
    veh = vehicle()
    curvature, gradient, step = track()
    n = len(curvature)
    # Deploy hard out of the corners, nothing at the end of the straights. Kept clear
    # of the lap's seam, which the inversion does not trust on real data either.
    deploy = np.zeros(n)
    for start in (20, n // 2 + 20):
        deploy[start:start + 120] = 1.0
    curvature, gradient, step, res, throttle, brake = forward(deploy, veh)

    inferred = infer_deployment(
        res.speed_mps, throttle, brake, curvature, gradient, step, veh,
        res.lap_time_s, smooth_window_m=0.0,
    )
    assert inferred.energy_deployed_j == pytest.approx(res.energy_deployed_j, rel=0.05)
    assert inferred.unexplained_j < 0.02 * res.energy_deployed_j
    # Deployment is found where it was applied, not where it was not.
    on = deploy > 0
    assert inferred.deploy_power_w[on][10:-10].mean() > 5 * max(
        inferred.deploy_power_w[~on][10:-10].mean(), 1.0
    )


def test_a_weaker_engine_leaves_energy_unexplained():
    veh = vehicle()
    n = len(track()[0])
    curvature, gradient, step, res, throttle, brake = forward(np.ones(n), veh)

    honest = infer_deployment(res.speed_mps, throttle, brake, curvature, gradient,
                              step, veh, res.lap_time_s, smooth_window_m=0.0)
    weak = infer_deployment(res.speed_mps, throttle, brake, curvature, gradient,
                            step, vehicle(p_ice_w=250_000.0), res.lap_time_s,
                            smooth_window_m=0.0)
    assert weak.unexplained_j > honest.unexplained_j
    assert weak.energy_deployed_j >= honest.energy_deployed_j


def test_ice_power_floor_sits_at_or_below_the_true_engine():
    veh = vehicle()
    n = len(track()[0])
    curvature, gradient, step, res, throttle, brake = forward(np.ones(n), veh)
    floor = ice_power_floor(res.speed_mps, throttle, brake, curvature, gradient, step,
                            veh, res.lap_time_s, smooth_window_m=0.0)
    # The lap was driven with a 400 kW engine deploying the full ceiling, so an engine
    # weaker than that cannot explain it, and one at least that strong must.
    assert 250_000.0 < floor <= 400_000.0 + 5_000.0


def test_grip_scale_raises_corner_speed_and_lowers_lap_time():
    curvature, gradient, step = track()
    n = len(curvature)
    slow = simulate_lap(curvature, gradient, step, vehicle(grip_scale=1.0),
                        np.full(n, 0.5), BatteryState(soc_j=2_000_000.0))
    fast = simulate_lap(curvature, gradient, step, vehicle(grip_scale=1.15),
                        np.full(n, 0.5), BatteryState(soc_j=2_000_000.0))
    assert fast.lap_time_s < slow.lap_time_s
    assert fast.speed_mps.min() > slow.speed_mps.min()


def test_low_drag_state_only_applies_under_power_on_a_straight():
    veh = vehicle()
    v = 80.0
    assert veh.drag_area(v, 0.0, driving=True) == pytest.approx(0.906)
    assert veh.drag_area(v, 0.0, driving=False) == pytest.approx(0.968)
    assert veh.drag_area(v, 1.0 / 100.0, driving=True) == pytest.approx(0.968)
    assert vehicle(cd_a_low=None).drag_area(v, 0.0, driving=True) == pytest.approx(0.968)
